### ISSUE TITLE
Avoid using Microsoft TTF fonts - possible license incompatibility and restrictions

### ISSUE THREAD

**Issue by MagicFab** [piwik/travis-scripts#3]
I've been asked to file this bug following internal discussion about problems introduced when using Microsoft TTF fonts, mostly problematic download / update mechanisms as they're non-free, not part of Debian main repositories (per DFSG) and not maintained by the Piwik community. This bug is about including such font files directly embedded.

Also at issue is the incompatibility with Piwik's GPL license: Microsoft TTF fonts require accepting an EULA license restricting non-commercial use, with possible anytime, unilateral rights termination policy, distribution restrictions and other restrictions.

A possible alternative would be to use Liberation fonts:
https://fedorahosted.org/liberation-fonts/

Commit embedding such fonts here:
https://github.com/piwik/travis-scripts/pull/2/files

Quick search of other uses of such fonts in Piwik CSS:
https://github.com/piwik/piwik/search?utf8=%E2%9C%93&q=Verdana&type=Code

Ref: 
- http://www.microsoft.com/typography/fontpack/eula.htm
- https://en.wikipedia.org/wiki/Core_fonts_for_the_Web#Program_termination_and_software_licence_agreement_issues

**Comment by mattab** [comment]
Note: we bundle the fonts in the Git repository via sub-module, but the actual TTF files are not included in the [Piwik builds](http://builds.piwik.org/) - our build package tool deletes the content of `tests/` folder where these fonts are. so I think it's fine from licensing point of view. 

> Quick search of other uses of such fonts in Piwik CSS:
https://github.com/piwik/piwik/search?utf8=%E2%9C%93&q=Verdana&type=Code

IMO it is not an issue to reference `Verdana` in CSS rules, because  on a free/libre system the browser / clients will default to whatever system font there is next available (ie. free/libre font).

**Comment by MagicFab** [comment]
Redistribution is not the only possible licensing issue, as I detailed in the first report.

**Comment by mattab** [comment]
We may change fonts in Piwik later (ie. in Piwik 3) so fonts used in UI tests may change then.
